// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: ROBOT

#ifndef _ROBOT_UI_H
#define _ROBOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t * ui_START;
void ui_event_STARTBUTTON(lv_event_t * e);
extern lv_obj_t * ui_STARTBUTTON;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_WLAN;
extern lv_obj_t * ui_WLANIP;
extern lv_obj_t * ui_ETHIP1;
extern lv_obj_t * ui_ETH;
extern lv_obj_t * ui_TIRETTE;
extern lv_obj_t * ui_IMU;
extern lv_obj_t * ui_LIDAR;
extern lv_obj_t * ui_SUIVIT;
extern lv_obj_t * ui_PCA;
extern lv_obj_t * ui_TIRETTESTATE;
extern lv_obj_t * ui_IMUSTATE;
extern lv_obj_t * ui_LIDARSTATE;
extern lv_obj_t * ui_SUIVITSTATE;
extern lv_obj_t * ui_PCASTATE;
extern lv_obj_t * ui_CAPTD;
extern lv_obj_t * ui_CAPTD1;
extern lv_obj_t * ui_UARTM;
extern lv_obj_t * ui_CAPTDSTATE;
extern lv_obj_t * ui_CAPTGSTATE;
extern lv_obj_t * ui_UARTMSTATE;
extern lv_obj_t * ui_UARTC;
extern lv_obj_t * ui_UARTCSTATE;
extern lv_obj_t * ui_ROS;
extern lv_obj_t * ui_ROSSTATE;
extern lv_obj_t * ui_ROBOTCOLOR;
extern lv_obj_t * ui_COLOR;
void ui_event_COLORBLUE(lv_event_t * e);
extern lv_obj_t * ui_COLORBLUE;
extern lv_obj_t * ui_BLEU;
void ui_event_COLORYELLOW(lv_event_t * e);
extern lv_obj_t * ui_COLORYELLOW;
extern lv_obj_t * ui_YELLOW;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_STRATEGIE;
void ui_event_STARTBUTTON1(lv_event_t * e);
extern lv_obj_t * ui_STARTBUTTON1;
void ui_event_BACKBUTTON(lv_event_t * e);
extern lv_obj_t * ui_BACKBUTTON;
extern lv_obj_t * ui_STRATIMAGE;
void ui_event_STRAT1(lv_event_t * e);
extern lv_obj_t * ui_STRAT1;
void ui_event_STRAT2(lv_event_t * e);
extern lv_obj_t * ui_STRAT2;
void ui_event_STRAT3(lv_event_t * e);
extern lv_obj_t * ui_STRAT3;
void ui_event_STRAT4(lv_event_t * e);
extern lv_obj_t * ui_STRAT4;
void ui_event_STRAT5(lv_event_t * e);
extern lv_obj_t * ui_STRAT5;
void ui_event_STRAT6(lv_event_t * e);
extern lv_obj_t * ui_STRAT6;
void ui_event_STRAT7(lv_event_t * e);
extern lv_obj_t * ui_STRAT7;
extern lv_obj_t * ui_MATCH;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_SCORE;
extern lv_obj_t * ui_SCOREVALUE;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui____initial_actions0;
extern int flag;
//extern char COULEUR;

LV_IMG_DECLARE(ui_img_100247398);    // assets/start-button.png
LV_IMG_DECLARE(ui_img_pngegg_png);    // assets/pngegg.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/BACK.png
LV_IMG_DECLARE(ui_img_1204001689);    // assets/test (1).png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_256_png);    // assets/256.png
LV_IMG_DECLARE(ui_img_pngwing_com_png);    // assets/pngwing.com.png
LV_IMG_DECLARE(ui_img_1610686690);    // assets/—Pngtree—the start button_286495.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
