// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: ROBOT

#include "ui.h"
//int flag = 0;

void SET_BLUECOLOR(lv_event_t * e)
{
	// Your code here
}

void SET_YELLOWCOLOR(lv_event_t * e)
{
	// Your code here
}

void RESET(lv_event_t * e){
	//flag = 1;

}
void STRATIMAGE1(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE2(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE3(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE4(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE5(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE6(lv_event_t * e)
{
	// Your code here
}

void STRATIMAGE7(lv_event_t * e)
{
	// Your code here
}
