// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: ROBOT

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SET_BLUECOLOR(lv_event_t * e);
void SET_YELLOWCOLOR(lv_event_t * e);
void RESET(lv_event_t * e);
void STRATIMAGE1(lv_event_t * e);
void STRATIMAGE2(lv_event_t * e);
void STRATIMAGE3(lv_event_t * e);
void STRATIMAGE4(lv_event_t * e);
void STRATIMAGE5(lv_event_t * e);
void STRATIMAGE6(lv_event_t * e);
void STRATIMAGE7(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/

#endif

#endif
